[package]
name = "yao-millionare"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rsa = "0.5.0"
num = "0.4.0"
num-primes = "0.1.1"
